baseURL = 'https://y-ashaswini.github.io/'
locale = 'en-us'
title = 'Dynamic Equillibrium'
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
      
[permalinks]
    blog = "/blog/:title/"

[params]
    env = "production"
    defaultTheme = "dark" 
    disableThemeToggle = false
    # PaperMod Profile Mode
    [params.profileMode]
        enabled = true
        title = "Yashaswini Shivathaya"
        subtitle = "yashaswinishivathaya@gmail.com"

    [params.label]
        text = "Dynamic Equillibrium"


    