baseURL = 'https://y-ashaswini.github.io/'
locale = 'en-us'
title = 'Dynamic Equillibrium'
theme = "PaperMod"

[permalinks]
    blog = "/blog/:title/"

[params]
    env = "production"
    defaultTheme = "dark" 
    disableThemeToggle = false
    # PaperMod Profile Mode
    [params.profileMode]
        enabled = true
        title = "Yashaswini Shivathaya"
        subtitle = "yashaswinishivathaya@gmail.com"
        #imageUrl = "https://raw.githubusercontent.com/google/material-design-icons/master/src/action/terminal/materialicons/24px.svg" # Or your own avatar
        #imageWidth = 120
        #imageHeight = 120
        [[params.profileMode.buttons]]
            name = "click to find raw thoughts"
            url = "/blog"
        #[[params.profileMode.buttons]]
        #    name = "The Dossier (Resume)"
        #    url = "/kronos/resume"

    [params.label]
        text = "<homepage/>"