baseURL = 'https://y-ashaswini.github.io/'
locale = 'en-us'
title = 'Dynamic Equillibrium'
theme = "PaperMod"

[permalinks]
    blog = "/blog/:title/"

[params]
env = "production"
    ShowReadingTime = true
    displayFullContent = false
    ShowBreadCrumbs = true